r"""
generated by json2python-models v0.2.1 at Thu Apr 15 16:32:24 2021
command: C:\Users\sg-okubo\miniconda3\envs\optical-flow\Scripts\json2models -m Config configs\config.json -f dataclasses --max-strings-literals 0
"""
from dataclasses import dataclass

from dataclasses_json import dataclass_json


@dataclass_json
@dataclass
class OutputVideoSize:
    height: int
    width: int

